/**
 * brain-app bridge client — talks to the brain host shell via postMessage.
 *
 * This app runs as a sandboxed iframe inside a BrainFoundry brain. It cannot
 * call the brain API directly. It posts an `llm.complete` intent to the parent
 * (the host shell at ui/pages/apps/[id].js), which holds the credentials and a
 * loop permit and proxies the request to the brain's /chat/rag — so the AI
 * Tutor answer is generated by the operator's BYOK model, over the brain's own
 * corpus.
 *
 * Contract (brain-app/v1, llm.complete intent):
 *   iframe -> host:  { type:'llm.complete', request_id, payload:{ messages } }
 *   host -> iframe:  { type:'reply', request_id, ok, result?, error? }
 *   result = { text, model, sources }
 *   error codes: permission_denied | missing_messages | permit_failed
 *              | llm_complete_failed | llm_complete_network_error
 */

export interface BridgeMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

export interface LlmResult {
  /** The generated completion. */
  text: string;
  /** The model the brain used (operator's BYOK selection). */
  model: string;
  /** Corpus documents the RAG step retrieved. */
  sources: string[];
}

/** Generous — /chat/rag on a cold brain can take a while before first token. */
const REPLY_TIMEOUT_MS = 120_000;

let counter = 0;
function nextRequestId(): string {
  counter += 1;
  return `cell-studio-${Date.now()}-${counter}`;
}

/**
 * True when the app is running embedded inside a brain (i.e. inside an iframe
 * with a parent it can postMessage to). When false, the AI Tutor cannot reach
 * a brain and the UI should say so instead of spinning.
 */
export function isInBrain(): boolean {
  return typeof window !== "undefined" && window.parent !== window;
}

/**
 * Ask the host brain to generate a completion. Resolves with the generated
 * text, the model used, and the corpus sources. Rejects with an Error whose
 * message is the bridge error code (or a local code: not_in_brain,
 * llm_complete_timeout).
 */
export function llmComplete(messages: BridgeMessage[]): Promise<LlmResult> {
  return new Promise((resolve, reject) => {
    if (!isInBrain()) {
      reject(new Error("not_in_brain"));
      return;
    }

    const request_id = nextRequestId();
    let settled = false;

    const finish = (fn: () => void) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      window.removeEventListener("message", onReply);
      fn();
    };

    const timer = setTimeout(
      () => finish(() => reject(new Error("llm_complete_timeout"))),
      REPLY_TIMEOUT_MS
    );

    function onReply(event: MessageEvent) {
      const msg = event.data;
      if (!msg || typeof msg !== "object") return;
      if (msg.type !== "reply" || msg.request_id !== request_id) return;
      finish(() => {
        if (msg.ok && msg.result) {
          resolve({
            text: String(msg.result.text || ""),
            model: String(msg.result.model || ""),
            sources: Array.isArray(msg.result.sources) ? msg.result.sources : [],
          });
        } else {
          const code = (msg.error && msg.error.code) || "llm_complete_failed";
          reject(new Error(String(code)));
        }
      });
    }

    window.addEventListener("message", onReply);
    window.parent.postMessage(
      { type: "llm.complete", request_id, payload: { messages } },
      "*"
    );
  });
}

/** Human-readable text for a bridge error code, for the tutor panel. */
export function bridgeErrorMessage(code: string): string {
  switch (code) {
    case "not_in_brain":
      return "The AI Tutor answers when this app runs inside a BrainFoundry brain. Install it via Settings -> Apps.";
    case "llm_complete_timeout":
      return "The brain took too long to answer. It may be cold — try again in a moment.";
    case "permission_denied":
      return "This app is not permitted to invoke the brain's model. Re-approve it in Settings -> Apps.";
    case "permit_failed":
      return "The brain could not mint a loop permit for this request. Try again.";
    default:
      return "The brain could not answer that. Try again, or rephrase the question.";
  }
}
